using System;
using System.Threading.Tasks;
using LifeLink.Common;
using LifeLink.DTOs.Common;
using LifeLink.DTOs.Notification;
using LifeLink.Services.Notification;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LifeLink.Controllers
{
    [ApiController]
    [Route("api/notifications")]
    [AllowSuspendedAccess]
    public class NotificationsController : ControllerBase
    {
        private readonly INotificationAgentService _notificationService;

        public NotificationsController(INotificationAgentService notificationService)
        {
            _notificationService = notificationService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllNotifications()
        {
            var list = await _notificationService.GetAllNotificationsAsync();
            return Ok(list);
        }

        [HttpGet("user/{userId:guid}")]
        public async Task<IActionResult> GetUserNotifications(Guid userId)
        {
            var list = await _notificationService.GetNotificationsForUserAsync(userId);
            return Ok(list);
        }

        /// <summary>
        /// Creates a recommendation notification generated by AI Agents.
        /// </summary>
        [HttpPost("recommendations")]
        [ProducesResponseType(typeof(ApiResponse<NotificationResponseDto>), StatusCodes.Status201Created)]
        [ProducesResponseType(typeof(ApiResponse<object>), StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> CreateRecommendationNotification([FromBody] CreateRecommendationNotificationDto request)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = await _notificationService.CreateRecommendationNotificationAsync(request);
            return CreatedAtAction(
                nameof(GetAllNotifications),
                new { id = result.NotificationId },
                ApiResponse<NotificationResponseDto>.Ok(result, "Recommendation notification created successfully.")
            );
        }
    }
}
